name: Build Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build macOS application
        run: pyinstaller YouTubeDownloader.spec
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTubeDownloader-macOS
          path: dist/YouTubeDownloader.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Windows application
        run: pyinstaller YouTubeDownloader.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTubeDownloader-Windows
          path: dist/YouTubeDownloader
